//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Marv.LineAndSectionOverviewService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LineAndSectionOverviewServiceSoap", Namespace="http://brix.dnv.com/BRIXProject/")]
    public partial class LineAndSectionOverviewService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private BRIXAuthenticationHeader bRIXAuthenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSectionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetComponentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHotspotsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetThreatGroupsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LineAndSectionOverviewService() {
            this.Url = global::Marv.Properties.Settings.Default.Marv_LineAndSectionOverviewService_LineAndSectionOverviewService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public BRIXAuthenticationHeader BRIXAuthenticationHeaderValue {
            get {
                return this.bRIXAuthenticationHeaderValueField;
            }
            set {
                this.bRIXAuthenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLinesCompletedEventHandler GetLinesCompleted;
        
        /// <remarks/>
        public event GetSectionsCompletedEventHandler GetSectionsCompleted;
        
        /// <remarks/>
        public event GetSectionCompletedEventHandler GetSectionCompleted;
        
        /// <remarks/>
        public event GetComponentsCompletedEventHandler GetComponentsCompleted;
        
        /// <remarks/>
        public event GetEventsCompletedEventHandler GetEventsCompleted;
        
        /// <remarks/>
        public event GetEventCompletedEventHandler GetEventCompleted;
        
        /// <remarks/>
        public event GetHotspotsCompletedEventHandler GetHotspotsCompleted;
        
        /// <remarks/>
        public event GetThreatGroupsCompletedEventHandler GetThreatGroupsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://brix.dnv.com/BRIXProject/GetLines", RequestNamespace="http://brix.dnv.com/BRIXProject/", ResponseNamespace="http://brix.dnv.com/BRIXProject/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LineSummaryDTO[] GetLines() {
            object[] results = this.Invoke("GetLines", new object[0]);
            return ((LineSummaryDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLinesAsync() {
            this.GetLinesAsync(null);
        }
        
        /// <remarks/>
        public void GetLinesAsync(object userState) {
            if ((this.GetLinesOperationCompleted == null)) {
                this.GetLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLinesOperationCompleted);
            }
            this.InvokeAsync("GetLines", new object[0], this.GetLinesOperationCompleted, userState);
        }
        
        private void OnGetLinesOperationCompleted(object arg) {
            if ((this.GetLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLinesCompleted(this, new GetLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://brix.dnv.com/BRIXProject/GetSections", RequestNamespace="http://brix.dnv.com/BRIXProject/", ResponseNamespace="http://brix.dnv.com/BRIXProject/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SectionSummaryDTO[] GetSections(System.Guid lineOid) {
            object[] results = this.Invoke("GetSections", new object[] {
                        lineOid});
            return ((SectionSummaryDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSectionsAsync(System.Guid lineOid) {
            this.GetSectionsAsync(lineOid, null);
        }
        
        /// <remarks/>
        public void GetSectionsAsync(System.Guid lineOid, object userState) {
            if ((this.GetSectionsOperationCompleted == null)) {
                this.GetSectionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSectionsOperationCompleted);
            }
            this.InvokeAsync("GetSections", new object[] {
                        lineOid}, this.GetSectionsOperationCompleted, userState);
        }
        
        private void OnGetSectionsOperationCompleted(object arg) {
            if ((this.GetSectionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSectionsCompleted(this, new GetSectionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://brix.dnv.com/BRIXProject/GetSection", RequestNamespace="http://brix.dnv.com/BRIXProject/", ResponseNamespace="http://brix.dnv.com/BRIXProject/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SectionSummaryDTO GetSection(System.Guid sectionOid) {
            object[] results = this.Invoke("GetSection", new object[] {
                        sectionOid});
            return ((SectionSummaryDTO)(results[0]));
        }
        
        /// <remarks/>
        public void GetSectionAsync(System.Guid sectionOid) {
            this.GetSectionAsync(sectionOid, null);
        }
        
        /// <remarks/>
        public void GetSectionAsync(System.Guid sectionOid, object userState) {
            if ((this.GetSectionOperationCompleted == null)) {
                this.GetSectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSectionOperationCompleted);
            }
            this.InvokeAsync("GetSection", new object[] {
                        sectionOid}, this.GetSectionOperationCompleted, userState);
        }
        
        private void OnGetSectionOperationCompleted(object arg) {
            if ((this.GetSectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSectionCompleted(this, new GetSectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://brix.dnv.com/BRIXProject/GetComponents", RequestNamespace="http://brix.dnv.com/BRIXProject/", ResponseNamespace="http://brix.dnv.com/BRIXProject/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ComponentSummaryDto[] GetComponents(System.Guid sectionOid) {
            object[] results = this.Invoke("GetComponents", new object[] {
                        sectionOid});
            return ((ComponentSummaryDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetComponentsAsync(System.Guid sectionOid) {
            this.GetComponentsAsync(sectionOid, null);
        }
        
        /// <remarks/>
        public void GetComponentsAsync(System.Guid sectionOid, object userState) {
            if ((this.GetComponentsOperationCompleted == null)) {
                this.GetComponentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetComponentsOperationCompleted);
            }
            this.InvokeAsync("GetComponents", new object[] {
                        sectionOid}, this.GetComponentsOperationCompleted, userState);
        }
        
        private void OnGetComponentsOperationCompleted(object arg) {
            if ((this.GetComponentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetComponentsCompleted(this, new GetComponentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://brix.dnv.com/BRIXProject/GetEvents", RequestNamespace="http://brix.dnv.com/BRIXProject/", ResponseNamespace="http://brix.dnv.com/BRIXProject/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EventSummaryDto[] GetEvents(System.Guid sectionOid) {
            object[] results = this.Invoke("GetEvents", new object[] {
                        sectionOid});
            return ((EventSummaryDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEventsAsync(System.Guid sectionOid) {
            this.GetEventsAsync(sectionOid, null);
        }
        
        /// <remarks/>
        public void GetEventsAsync(System.Guid sectionOid, object userState) {
            if ((this.GetEventsOperationCompleted == null)) {
                this.GetEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventsOperationCompleted);
            }
            this.InvokeAsync("GetEvents", new object[] {
                        sectionOid}, this.GetEventsOperationCompleted, userState);
        }
        
        private void OnGetEventsOperationCompleted(object arg) {
            if ((this.GetEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEventsCompleted(this, new GetEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://brix.dnv.com/BRIXProject/GetEvent", RequestNamespace="http://brix.dnv.com/BRIXProject/", ResponseNamespace="http://brix.dnv.com/BRIXProject/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EventSummaryDto[] GetEvent(System.Guid eventOid) {
            object[] results = this.Invoke("GetEvent", new object[] {
                        eventOid});
            return ((EventSummaryDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEventAsync(System.Guid eventOid) {
            this.GetEventAsync(eventOid, null);
        }
        
        /// <remarks/>
        public void GetEventAsync(System.Guid eventOid, object userState) {
            if ((this.GetEventOperationCompleted == null)) {
                this.GetEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventOperationCompleted);
            }
            this.InvokeAsync("GetEvent", new object[] {
                        eventOid}, this.GetEventOperationCompleted, userState);
        }
        
        private void OnGetEventOperationCompleted(object arg) {
            if ((this.GetEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEventCompleted(this, new GetEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://brix.dnv.com/BRIXProject/GetHotspots", RequestNamespace="http://brix.dnv.com/BRIXProject/", ResponseNamespace="http://brix.dnv.com/BRIXProject/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HotspotSummaryDto[] GetHotspots(System.Guid sectionOid) {
            object[] results = this.Invoke("GetHotspots", new object[] {
                        sectionOid});
            return ((HotspotSummaryDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetHotspotsAsync(System.Guid sectionOid) {
            this.GetHotspotsAsync(sectionOid, null);
        }
        
        /// <remarks/>
        public void GetHotspotsAsync(System.Guid sectionOid, object userState) {
            if ((this.GetHotspotsOperationCompleted == null)) {
                this.GetHotspotsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotspotsOperationCompleted);
            }
            this.InvokeAsync("GetHotspots", new object[] {
                        sectionOid}, this.GetHotspotsOperationCompleted, userState);
        }
        
        private void OnGetHotspotsOperationCompleted(object arg) {
            if ((this.GetHotspotsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotspotsCompleted(this, new GetHotspotsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://brix.dnv.com/BRIXProject/GetThreatGroups", RequestNamespace="http://brix.dnv.com/BRIXProject/", ResponseNamespace="http://brix.dnv.com/BRIXProject/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThreatDto[] GetThreatGroups(System.Guid sectionOid) {
            object[] results = this.Invoke("GetThreatGroups", new object[] {
                        sectionOid});
            return ((ThreatDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetThreatGroupsAsync(System.Guid sectionOid) {
            this.GetThreatGroupsAsync(sectionOid, null);
        }
        
        /// <remarks/>
        public void GetThreatGroupsAsync(System.Guid sectionOid, object userState) {
            if ((this.GetThreatGroupsOperationCompleted == null)) {
                this.GetThreatGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetThreatGroupsOperationCompleted);
            }
            this.InvokeAsync("GetThreatGroups", new object[] {
                        sectionOid}, this.GetThreatGroupsOperationCompleted, userState);
        }
        
        private void OnGetThreatGroupsOperationCompleted(object arg) {
            if ((this.GetThreatGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetThreatGroupsCompleted(this, new GetThreatGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dnv.com/WebServices/BRIXSecurity/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.dnv.com/WebServices/BRIXSecurity/", IsNullable=false)]
    public partial class BRIXAuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private bool authenticatedField;
        
        private string valueField;
        
        private System.DateTime issueDateField;
        
        private System.DateTime expirationField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public bool authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brix.dnv.com/BRIXProject/")]
    public partial class ThreatDto {
        
        private System.Guid oidField;
        
        private string nameField;
        
        private ThreatDto[] subThreatsField;
        
        /// <remarks/>
        public System.Guid Oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public ThreatDto[] SubThreats {
            get {
                return this.subThreatsField;
            }
            set {
                this.subThreatsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brix.dnv.com/BRIXProject/")]
    public partial class HotspotSummaryDto {
        
        private System.Guid oidField;
        
        private string idField;
        
        private string nameField;
        
        private System.Guid sectionOidField;
        
        private decimal beginField;
        
        private decimal endField;
        
        private string mRefUnitField;
        
        /// <remarks/>
        public System.Guid Oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid SectionOid {
            get {
                return this.sectionOidField;
            }
            set {
                this.sectionOidField = value;
            }
        }
        
        /// <remarks/>
        public decimal Begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        public decimal End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public string MRefUnit {
            get {
                return this.mRefUnitField;
            }
            set {
                this.mRefUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brix.dnv.com/BRIXProject/")]
    public partial class EventSummaryDto {
        
        private System.Guid oidField;
        
        private string nameField;
        
        private string typeField;
        
        private string severityField;
        
        private System.Guid sectionOidField;
        
        private System.Nullable<decimal> beginField;
        
        private System.Nullable<decimal> endField;
        
        private string mRefUnitField;
        
        /// <remarks/>
        public System.Guid Oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid SectionOid {
            get {
                return this.sectionOidField;
            }
            set {
                this.sectionOidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public string MRefUnit {
            get {
                return this.mRefUnitField;
            }
            set {
                this.mRefUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brix.dnv.com/BRIXProject/")]
    public partial class ComponentSummaryDto {
        
        private System.Guid oidField;
        
        private string idField;
        
        private string nameField;
        
        private string typeField;
        
        private System.Guid sectionOidField;
        
        private decimal beginField;
        
        private decimal endField;
        
        private decimal lengthField;
        
        private string mRefUnitField;
        
        /// <remarks/>
        public System.Guid Oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid SectionOid {
            get {
                return this.sectionOidField;
            }
            set {
                this.sectionOidField = value;
            }
        }
        
        /// <remarks/>
        public decimal Begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        public decimal End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public decimal Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string MRefUnit {
            get {
                return this.mRefUnitField;
            }
            set {
                this.mRefUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brix.dnv.com/BRIXProject/")]
    public partial class SectionSummaryDTO {
        
        private System.Guid sectionOidField;
        
        private System.Guid lineOidField;
        
        private string sectionIdField;
        
        private string nameField;
        
        private string integrityManagementSchemeField;
        
        private decimal beginField;
        
        private decimal endField;
        
        private string mRefUnitField;
        
        private bool isDNVStandardField;
        
        private bool isOnshoreField;
        
        /// <remarks/>
        public System.Guid SectionOid {
            get {
                return this.sectionOidField;
            }
            set {
                this.sectionOidField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid LineOid {
            get {
                return this.lineOidField;
            }
            set {
                this.lineOidField = value;
            }
        }
        
        /// <remarks/>
        public string SectionId {
            get {
                return this.sectionIdField;
            }
            set {
                this.sectionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrityManagementScheme {
            get {
                return this.integrityManagementSchemeField;
            }
            set {
                this.integrityManagementSchemeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        public decimal End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public string MRefUnit {
            get {
                return this.mRefUnitField;
            }
            set {
                this.mRefUnitField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDNVStandard {
            get {
                return this.isDNVStandardField;
            }
            set {
                this.isDNVStandardField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOnshore {
            get {
                return this.isOnshoreField;
            }
            set {
                this.isOnshoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://brix.dnv.com/BRIXProject/")]
    public partial class LineSummaryDTO {
        
        private System.Guid lineOidField;
        
        private string lineIdField;
        
        private string nameField;
        
        private string lineFunctionField;
        
        private string groupField;
        
        private string productField;
        
        /// <remarks/>
        public System.Guid LineOid {
            get {
                return this.lineOidField;
            }
            set {
                this.lineOidField = value;
            }
        }
        
        /// <remarks/>
        public string LineId {
            get {
                return this.lineIdField;
            }
            set {
                this.lineIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string LineFunction {
            get {
                return this.lineFunctionField;
            }
            set {
                this.lineFunctionField = value;
            }
        }
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetLinesCompletedEventHandler(object sender, GetLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LineSummaryDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LineSummaryDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSectionsCompletedEventHandler(object sender, GetSectionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSectionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSectionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SectionSummaryDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SectionSummaryDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSectionCompletedEventHandler(object sender, GetSectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SectionSummaryDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SectionSummaryDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetComponentsCompletedEventHandler(object sender, GetComponentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetComponentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetComponentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ComponentSummaryDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ComponentSummaryDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetEventsCompletedEventHandler(object sender, GetEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EventSummaryDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EventSummaryDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetEventCompletedEventHandler(object sender, GetEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EventSummaryDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EventSummaryDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHotspotsCompletedEventHandler(object sender, GetHotspotsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotspotsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotspotsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HotspotSummaryDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HotspotSummaryDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetThreatGroupsCompletedEventHandler(object sender, GetThreatGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetThreatGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetThreatGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThreatDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThreatDto[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591