//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Marv.SegmentationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SegmentationServiceSoap", Namespace="http://synergi.dnv.com/pipeline")]
    public partial class SegmentationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private BRIXAuthenticationHeader bRIXAuthenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetSegmentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SegmentationService() {
            this.Url = global::Marv.Properties.Settings.Default.Marv_SegmentationService_SegmentationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public BRIXAuthenticationHeader BRIXAuthenticationHeaderValue {
            get {
                return this.bRIXAuthenticationHeaderValueField;
            }
            set {
                this.bRIXAuthenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSegmentsCompletedEventHandler GetSegmentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BRIXAuthenticationHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://synergi.dnv.com/pipeline/GetSegments", RequestNamespace="http://synergi.dnv.com/pipeline", ResponseNamespace="http://synergi.dnv.com/pipeline", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SegmentsViewModel GetSegments(string scopeOid, string[] profiledefinitions, string distanceunit, string cultureName) {
            object[] results = this.Invoke("GetSegments", new object[] {
                        scopeOid,
                        profiledefinitions,
                        distanceunit,
                        cultureName});
            return ((SegmentsViewModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetSegmentsAsync(string scopeOid, string[] profiledefinitions, string distanceunit, string cultureName) {
            this.GetSegmentsAsync(scopeOid, profiledefinitions, distanceunit, cultureName, null);
        }
        
        /// <remarks/>
        public void GetSegmentsAsync(string scopeOid, string[] profiledefinitions, string distanceunit, string cultureName, object userState) {
            if ((this.GetSegmentsOperationCompleted == null)) {
                this.GetSegmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSegmentsOperationCompleted);
            }
            this.InvokeAsync("GetSegments", new object[] {
                        scopeOid,
                        profiledefinitions,
                        distanceunit,
                        cultureName}, this.GetSegmentsOperationCompleted, userState);
        }
        
        private void OnGetSegmentsOperationCompleted(object arg) {
            if ((this.GetSegmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSegmentsCompleted(this, new GetSegmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dnv.com/WebServices/BRIXSecurity/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.dnv.com/WebServices/BRIXSecurity/", IsNullable=false)]
    public partial class BRIXAuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private bool authenticatedField;
        
        private string valueField;
        
        private System.DateTime issueDateField;
        
        private System.DateTime expirationField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public bool authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://synergi.dnv.com/pipeline")]
    public partial class SegmentViewModel {
        
        private string[] dataField;
        
        /// <remarks/>
        public string[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://synergi.dnv.com/pipeline")]
    public partial class Header {
        
        private string nameField;
        
        private string unitField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://synergi.dnv.com/pipeline")]
    public partial class SegmentsViewModel {
        
        private Header[] headersField;
        
        private SegmentViewModel[] segmentsField;
        
        /// <remarks/>
        public Header[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
        
        /// <remarks/>
        public SegmentViewModel[] Segments {
            get {
                return this.segmentsField;
            }
            set {
                this.segmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSegmentsCompletedEventHandler(object sender, GetSegmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSegmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSegmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SegmentsViewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SegmentsViewModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591