//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marv.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Vinod\\Data\\LongChang\\ECDA_MODEL 2015 02 05 Clean.net")]
        public string NetworkFileName {
            get {
                return ((string)(this["NetworkFileName"]));
            }
            set {
                this["NetworkFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\Scenario08\\Scenario08.marv-linedata")]
        public string LineDataFileName {
            get {
                return ((string)(this["LineDataFileName"]));
            }
            set {
                this["LineDataFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\Locations.csv")]
        public string LocationsFileName {
            get {
                return ((string)(this["LocationsFileName"]));
            }
            set {
                this["LocationsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\Scenario08\\LocationValues.json")]
        public string LocationValuesFileName {
            get {
                return ((string)(this["LocationValuesFileName"]));
            }
            set {
                this["LocationValuesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\ReferenceLocations.csv")]
        public string ReferenceLocationsFileName {
            get {
                return ((string)(this["ReferenceLocationsFileName"]));
            }
            set {
                this["ReferenceLocationsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\CriticalLocations.csv")]
        public string CriticalLocationsFileName {
            get {
                return ((string)(this["CriticalLocationsFileName"]));
            }
            set {
                this["CriticalLocationsFileName"] = value;
            }
        }
    }
}
